### ISSUE TITLE
Fixedsys 폰트의 사용 on windows 10

### ISSUE THREAD

**Issue by pkyoung0** [iPuTTY/iPuTTY#28]
Windows10에서 사용중입니다.

굴림체로 선택하는 경우 Unicode Mode on/off 상황에서 모두
제대로 한글이 표현됩니다. (cp949 or UTF8 로 translation이 설정됨)

그런데 Fixedsys 폰트로 사용하는 경우
일단 폰트의 적용이 제대로 되지 않습니다. (기존 putty는 잘됨)
영문 및 한글 모두 대체 폰트가 사용되어 표시됩니다.
그리고 Unicode Mode에서는 대체폰트가 사용되어 한글이 잘 나옵니다만,
Unicode Mode가 아닌 겨우 cp949 translation으로는 한글이 깨집니다.
대신 translation을 'Use font encoding'으로 하면 한글이 표시됩니다.

두가지가 별개의 문제인 것 같은데,  각각 해결 방법이 있을까요?
요약하면, 
1: Fixedsys 폰트가 제대로 적용되지 않음
2: Unicode Mode가 아닌 경우 translation을 CP949 대신 'Use font encoding' 을 적용

**Comment by Joungkyun** [comment]
일단 기본적으로 unicode mode가 아닐 경우, 해당 폰트의 script 가 한글로 설정이 되어 있어야 한글이 출력이 됩니다.

"https://github.com/iPuTTY/iPuTTY/issues/15 CP949 모드에서 한글 입출력 안되는 문제" 를 참고해 보세요.

그리고 fixedsys의 영문 대체 폰틑 사용은 확인을 해 보려 했는데, 전 fixedsys를 선택할 수가 없네요 ㅠㅠ
이 부분은 좀 더 확인을 해 보겠습니다.

**Comment by Joungkyun** [comment]
fixedsys 에서 해당 문제 확인은 했습니다. 왜 안되는지 찾아 봐야겠군요 ㅠㅠ

**Comment by Joungkyun** [comment]
#29 putty 0.70 update 이슈의 beta2 버전에 fix 되어 있으니 확인해 보시기 바랍니다.
