### ISSUE TITLE
Escape 키 치면  자동으로 영문입력모드로 전환

### ISSUE THREAD

**Issue by qqkookie** [iPuTTY/iPuTTY#43]
한글입력 모드에서 Escape 키를 치면 자동으로 영문입력 모드로 전환하게 할 수 없나요?
vi 등 editor 에서는 매우 자주 영문명령어 모드와 한글 입력 모드를 바꿔야 하는데
한글 편집 중일 때는 이게 매우 혼란스럽고 귀찮습니다.
그래서 편집중에 Escape 키를 치면 영문입력모드로 자동으로 전환되는 옵션이 있으면 좋겠습니다.
적어도 윈도우 버전에서는 이런 자동 영문입력 모드 전환이 되었으면 합니다.

**Comment by qqkookie** [comment]
제가 착각했군요. 죄송합니다. 이슈를 닫겠습니다.

**Comment by Joungkyun** [comment]
#12 에서 이미 구현 되었습니다.
