### ISSUE TITLE
iputty 프로그램 사용시 문제점

### ISSUE THREAD

**Issue by devilduo** [iPuTTY/iPuTTY#47]
서버 관리 업종에 종사중인 직장인입니다
기존에 putty를 쓰고 있다가 openssl 업데이트와 같이 서버 환경 변화로 구버전을 쓰지 못하여
해결책을 찾던중 이프로그램을 알게 되어 쓰고 있는데 문제가 있습니다

사용환경은 윈도우10 프로 64비트 버전의 클라이언트에서 해당 프로그램을 단독으로
사용시에는 별문제가 없는데 puttycm이라는 통합 관리 프로그램에 등록하여 사용시

여러대의 서버를 동시에 접근하면 글자가 표기 되지 않거나 실제로 특정 스크립트가 실행 되고 있는데
화면상에서 갱신이 안되는 문제가 발생 합니다

![1](https://user-images.githubusercontent.com/47246712/52124056-676c0780-266b-11e9-8c14-b9fbc79ddfa0.JPG)
![2](https://user-images.githubusercontent.com/47246712/52124057-676c0780-266b-11e9-9a3a-cbc3d9bb3cf9.JPG)

해당 증상이 나타나는 조건을 나열 하자면

1. 윈도우 10 64비트 한국 정식 버전에서 최신 업데이트후 
    puttycm 설치후 실행하여 iputty를 등록하여 설정

2. puttycm에 여러대의 서버 등록후 아이피 및 아이디 및 암호를 등록하여 해당 목록
    더블클릭시 자동 접속 되게 설정

3. 동시에 여러대의 서버를 클릭하여 동시에 접속 시도

4. 처음 접속한 서버외 다른 서버들이 화면에 아무것도 나오지 않지만 실제 접속된 형태라 
   엔터를 치면 프롬프트가 나오나 한 라인씩 빠짐

5. 이외 증상으로는 HP 유닉스 서버들의 서버 현황을 보는 GLANCE 라는 명령어 사용시
    실행후 응답이 없거나 화면이 깨지는데 창크기를 조절하면 정상 출력 (꼭 이프로그램 말고도
     실시간 수치가 변하는 프로그램들이 비슷한 증상을 보임, HP 유닉스에만 한정된게 아닌 증상)

**Comment by Joungkyun** [comment]
iputty 를 standalone 으로 동작 시키는데 문제가 없다면 이건 iputty 문제로 볼 수는 없습니다. 그리고 puttycm이 개발이 중단된 프로그램으로, putty layer 위에서 puttycm layout 이 동작하기 떄문에 puttycm 이 뭔짓을 하는 것인지 알 수 없으면 고치기도 힘이 듭니다.

puttycm이 개발 중단이 된것이 2012년 이기  때문에 어떤 기능을 지원하지 못해서 발생하는 문제인지 찾는 것도 쉽지 않을 것 같네요.

그리고, 일단 가장 중요한 것은 저는 재현이 되지를 않습니다.

또한, 현재 개발이 진행중인 super putty 를 이용해 보시는 것을 권장 합니다. puttycm 과 interface 가 거의 유사하고 puttycm 에서 동작하지 않는 drag and drop zmodem 전송도 지원이 됩니다.

**Comment by Joungkyun** [comment]
아, 그리고 randering 이 나중에 되는 부분은 opactiy 설정 때문일 수도 있습니다.
puttycm 이나 super putty 와 같은 프로그램들은 외부 프로그램을 embed 하는데, 이 경우 원본 프로그램의 display 옵션이 영향을 줄 수 있는 것 같습니다.

iputty 옵션에서 ```창 > 창 투명도 옵션``` 의 값이 255가 아니라면, 255로 변경을 한 후에 다시 테스트 해 보시기 바랍니다.

아마도 이 문제는 super putty 에서도 동일하게 발생할 것 같네요.

**Comment by devilduo** [comment]
> 아, 그리고 randering 이 나중에 되는 부분은 opactiy 설정 때문일 수도 있습니다.
> puttycm 이나 super putty 와 같은 프로그램들은 외부 프로그램을 embed 하는데, 이 경우 원본 프로그램의 display 옵션이 영향을 줄 수 있는 것 같습니다.
> 
> iputty 옵션에서 `창 > 창 투명도 옵션` 의 값이 255가 아니라면, 255로 변경을 한 후에 다시 테스트 해 보시기 바랍니다.
> 
> 아마도 이 문제는 super putty 에서도 동일하게 발생할 것 같네요.

감사 합니다 슈퍼 푸티라는게 있는줄 몰랐습니다 명절 끝나고 한번 테스트 해보겠습니다

**Comment by devilduo** [comment]
감사 합니다 말씀 하신데로 투명도 옵션 값을 255로 하니 정상적으로 됩니다 
정말 많은 도움이 되었습니다 
그리고 기능 추가 건의 하나 드리고 싶은데 iputty에 저장된 세션이나 설정값을 따로 추출 해서 저장 할수
있게 있게되면 좋겠습니다

**Comment by devilduo** [comment]
추가 문의 사항이 있는데 구버전에서는 되던게 안되서 문의 드립니다

예를 들어서 서버에 접속해서 프롬프트 뜬 다음   특정 파일이나 폴더를 더블 클릭하면
클립보드로 저장되어 다시 마우스 오른쪽 버튼으로 붙여 넣을수 있는데

avc^&^134 이라는 글자가 있다면 더블 클릭시 구버전은 전체 선택이 되는데
iputty는 저중에서 같은 속성의 문자 3개만 되거나 한줄 전체 선택이 되어 버립니다

**Comment by Joungkyun** [comment]
구버전이라는 것이 어떤 버전인지 알 수가 없죠. 그리고 original putty 를 말씀 하시는 듯 한데, 해당 영역은 original putty 의 기능을 그대로 이용하는 부분 입니다. 별로 수정할 일은 없을 듯 싶습니다.

세션 설정값 추출은 고민을 좀 해 볼 사항이기는 한데, 현재 상태에서도 registry 에 저장하지 말고 file 로 저장하면 되기는 합니다. 다만 설정을 파일로 저장하는 경우, 이 값이 저장되지 않는 문제는 고민 중이기는 합니다.

그리고 하나의 이슈에 여러개의 이슈를 올리지 않는 것이 좋습니다. 제 입장에서는 이 이슈가 종료 되었기 때문에 close 할 거 거든요 😋
